[package]
name = "ccdi-cde"
version.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
indexmap.workspace = true
introspect.workspace = true
rand.workspace = true
regex.workspace = true
serde.workspace = true
serde_json.workspace = true
url.workspace = true
utoipa.workspace = true
