[package]
name = "ccdi-cde"
version = "0.1.0"
license.workspace = true
edition.workspace = true

[dependencies]
rand.workspace = true
serde.workspace = true
serde_json.workspace = true
utoipa.workspace = true
