[package]
name = "ccdi-cde"
authors = [
    "clay.mcleod@stjude.org"
]
description = "Common data elements for the CCDI Federation API"
version.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
indexmap.workspace = true
introspect.workspace = true
lazy_static.workspace = true
rand.workspace = true
regex.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_with.workspace = true
url.workspace = true
utoipa.workspace = true
