[package]
name = "ccdi-openapi"
version.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
ccdi-cde = { path = "../ccdi-cde" }
ccdi-models = { path = "../ccdi-models" }
ccdi-server = { path = "../ccdi-server" }
utoipa.workspace = true
