[package]
name = "ccdi-server"
version.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
actix-web.workspace = true
ccdi-cde = { path = "../ccdi-cde" }
ccdi-models = { path = "../ccdi-models" }
chrono.workspace = true
clap.workspace = true
indexmap.workspace = true
itertools = "0.11.0"
introspect.workspace = true
lazy_static = "1.4.0"
log.workspace = true
mime.workspace = true
rand.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_with.workspace = true
url = { version = "2", features = ["serde"] }
utoipa.workspace = true
