[package]
name = "ccdi-server"
version.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
actix-web.workspace = true
ccdi-cde = { path = "../ccdi-cde" }
ccdi-models = { path = "../ccdi-models" }
indexmap.workspace = true
log.workspace = true
mime.workspace = true
rand.workspace = true
serde.workspace = true
serde_json.workspace = true
utoipa.workspace = true
