[package]
name = "ccdi-spec"
version = "0.1.0"
license.workspace = true
edition.workspace = true

[dependencies]
actix-web.workspace = true
env_logger = "0.10.0"
ccdi-cde = { path = "../ccdi-cde", version = "0.1.0" }
ccdi-models = { path = "../ccdi-models", version = "0.1.0" }
ccdi-openapi = { path = "../ccdi-openapi", version = "0.1.0" }
ccdi-server = { path = "../ccdi-server", version = "0.1.0" }
clap = { version = "4.4.6", features = ["derive"] }
log.workspace = true
utoipa.workspace = true
utoipa-swagger-ui.workspace = true
