[package]
name = "ccdi-models"
version.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
ccdi-cde = { path = "../ccdi-cde" }
indexmap.workspace = true
macropol = "0.1.3"
rand.workspace = true
regex.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_test.workspace = true
utoipa.workspace = true
