name: Specification

on:
    push:
        branches:
            - main
    pull_request:

jobs:
    matches:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Update Rust
              run: rustup update nightly && rustup default nightly
            - run: |
                  cd packages
                  cargo run --all-features --bin ccdi-spec generate > ../current-swagger.yml
            - run: |
                  if ! diff swagger.yml current-swagger.yml; then
                    exit 1
                  fi
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: "latest"
            - name: Install spectral
              run: npm install -g @stoplight/spectral-cli
            - run: spectral lint swagger.yml
